### PR TITLE
Enhancement: Normalize composer.json

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] normalizes `composer.json`

❗️ Blocked by #53.

💁‍♂️ I ran

```
$ composer global require localheinz/composer-normalize
```

followed by

```
$ composer normalize
```

For reference, see https://github.com/localheinz/composer-normalize.

### CODE REVIEW

**Comment by keradus** [comment]
>  Blocked by #53.

how is that ?

**Comment by localheinz** [comment]
@keradus 

Indirectly, as the build for current `master` is broken!

**Comment by johnkary** [comment]
@localheinz Thank you for building such a useful tool!

**Comment by localheinz** [comment]
Thank you, @johnkary!

**Pull request merged**
