### PR TITLE
Allow PHPUnit 8

### LINKED ISSUE #52: Compatibility with phpunit 8?

### PR DESCRIPTION
**Pull request by Engerim**
* run tests with phpunit 8.0
* allow failures for dev-master runs
* fix #52

### CODE REVIEW

**Comment by johnkary** [comment]
Hi @Engerim, Thank you for adding this support to the build matrix! Looks like things are working well against PHPUnit 8.

Could you please see my comment about having removed nightly from the build matrix?

**Comment by Engerim** [comment]
Hi @johnkary I don't see any comment about the nightly build, but I can add the nightly php again

**Comment by johnkary** [comment]
@Engerim Yes, could we please add `- nightly` back to PHP build matrix?

**Comment by Engerim** [comment]
Nightly is added again, but with allowed failures.  php nightly is for now php 8.0.0-dev instead of 7.4.0-dev so i allow them to fail for now.
See also this tweet and comments https://twitter.com/kelunik/status/1094228271942848518?s=21

**Comment by bmaziere** [comment]
any plan to merge/release this @johnkary ? love this library and would be glad to keep using it with phpunit8 ;)
could also help to preprare a next version as TestListener interface seems deprecated now with phpunit8 if you want ;)

**Comment by Engerim** [comment]
ping @johnkary everything works

**Comment by johnkary** [comment]
@Engerim Thank you for your help to allow PHPUnit 8 compatibility!

**Pull request merged**
