### PR TITLE
Fix for PHPUnit 9.5 and newer (fix removed removed getAnnotations() method)

### LINKED ISSUE #72: Fix needed for phpunit 9.5
see https://github.com/sebastianbergmann/phpunit/issues/4519#issuecomment-737985677

issue introduced in commit: https://github.com/sebastianbergmann/phpunit/commit/68582043e149039cfa3596b42ed35753dcf54fb2

### PR DESCRIPTION
**Pull request by mvorisek**
fixes #72 (here is also described the issue)

### CODE REVIEW

**Comment by mvorisek** [comment]
@johnkary All users using the latest PHPUnit 9.5.0 are affected, please merge asap and issue a fix release. Thanks!

**Comment by elijahchancey** [comment]
Please merge this!

**Comment by tomasnorre** [comment]
I can confirm that this is working.

**Comment by johnkary** [comment]
Thank you, @mvorisek!

**Comment by johnkary** [comment]
Version `v3.3.0` has been tagged including this fix.

**Pull request merged**
